### ISSUE TITLE
TCP connected device (Speculos): no response sent back (Request timeout)

### ISSUE THREAD

**Issue by yogh333** [ledger-community/rust-ledger#1] opened 2023-06-16 15:45 UTC
Hello,

 I did a few tests with Speculos and sometimes, when sending APDUs, the response is not sent back and an `Error: Request timeout` is returned in place.

For instance, when using the following command: 
`cargo run -p ledger-cli -- --filters tcp --log-level "debug" apdu --cla 0x80 --ins 3 --p1 1 "07e00d496e324876bbc8531f2d9a82bf154d1a04a50218ee74cdd372f75a551a00000000000000000000000000000000000000000000000000038d7ea4c680000000000000000000000000000000000000000000000000534e5f474f45524c49000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001"`

the proper output is the following:
```
DEBUG ledger_cli: args: Args { cmd: Apdu { cla: 128, ins: 3, p1: 1, p2: 0, data: ApduData([7, 224, 13, 73, 110, 50, 72, 118, 187, 200, 83, 31, 45, 154, 130, 191, 21, 77, 26, 4, 165, 2, 24, 238, 116, 205, 211, 114, 247, 90, 85, 26, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 141, 126, 164, 198, 128, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 83, 78, 95, 71, 79, 69, 82, 76, 73, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]) }, index: 0, filters: Tcp, timeout: Duration(3s), log_level: LevelFilter::DEBUG }
DEBUG ledger_lib::transport: Initialising GenericTransport
DEBUG ledger_lib::provider::context: Starting ledger provider task
DEBUG ledger_lib::provider::context: LedgerProvider request: List(Tcp)
DEBUG ledger_lib::transport::tcp: Listing TCP devices
DEBUG ledger_lib::transport::tcp: devices: [LedgerInfo { model: Unknown(0), conn: Tcp(TcpInfo { addr: 127.0.0.1:1237 }) }]
DEBUG ledger_lib::provider::context: LedgerProvider response: Devices([LedgerInfo { model: Unknown(00), conn: Tcp(TcpInfo { addr: 127.0.0.1:1237 }) }])
DEBUG ledger_cli: Connecting to device: LedgerInfo { model: Unknown(0), conn: Tcp(TcpInfo { addr: 127.0.0.1:1237 }) }
DEBUG ledger_lib::provider::context: LedgerProvider request: Connect(LedgerInfo { model: Unknown(00), conn: Tcp(TcpInfo { addr: 127.0.0.1:1237 }) })
DEBUG ledger_lib::transport: Connecting to device: LedgerInfo { model: Unknown(0), conn: Tcp(TcpInfo { addr: 127.0.0.1:1237 }) }
DEBUG ledger_lib::transport::tcp: Connecting to: TcpInfo { addr: 127.0.0.1:1237 }
DEBUG ledger_lib::provider::context: Connected device 0: TCP 127.0.0.1:1237
DEBUG ledger_lib::provider::context: LedgerProvider response: Handle(00)
DEBUG ledger_lib::provider::context: LedgerProvider request: Req(00, [80, 03, 01, 00, c0, 07, e0, 0d, 49, 6e, 32, 48, 76, bb, c8, 53, 1f, 2d, 9a, 82, bf, 15, 4d, 1a, 04, a5, 02, 18, ee, 74, cd, d3, 72, f7, 5a, 55, 1a, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 03, 8d, 7e, a4, c6, 80, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 53, 4e, 5f, 47, 4f, 45, 52, 4c, 49, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 01], 3s)
DEBUG ledger_lib::transport::tcp: TX: [00, 00, 00, c5, 80, 03, 01, 00, c0, 07, e0, 0d, 49, 6e, 32, 48, 76, bb, c8, 53, 1f, 2d, 9a, 82, bf, 15, 4d, 1a, 04, a5, 02, 18, ee, 74, cd, d3, 72, f7, 5a, 55, 1a, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 03, 8d, 7e, a4, c6, 80, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 53, 4e, 5f, 47, 4f, 45, 52, 4c, 49, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 01]
DEBUG ledger_lib::transport::tcp: RX: [00, 00, 00, 01, 00, 90, 00]
DEBUG ledger_lib::provider::context: LedgerProvider response: Resp([00, 90, 00])
Response: 009000
DEBUG ledger_lib::provider::context: LedgerProvider request: Close(00)
DEBUG ledger_lib::provider::context: Closed device 0: Tcp(TcpInfo { addr: 127.0.0.1:1237 })
```
but sometimes it returns:
```
DEBUG ledger_cli: args: Args { cmd: Apdu { cla: 128, ins: 3, p1: 1, p2: 0, data: ApduData([7, 224, 13, 73, 110, 50, 72, 118, 187, 200, 83, 31, 45, 154, 130, 191, 21, 77, 26, 4, 165, 2, 24, 238, 116, 205, 211, 114, 247, 90, 85, 26, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 141, 126, 164, 198, 128, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 83, 78, 95, 71, 79, 69, 82, 76, 73, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]) }, index: 0, filters: Tcp, timeout: Duration(3s), log_level: LevelFilter::DEBUG }
DEBUG ledger_lib::transport: Initialising GenericTransport
DEBUG ledger_lib::provider::context: Starting ledger provider task
DEBUG ledger_lib::provider::context: LedgerProvider request: List(Tcp)
DEBUG ledger_lib::transport::tcp: Listing TCP devices
DEBUG ledger_lib::transport::tcp: devices: [LedgerInfo { model: Unknown(0), conn: Tcp(TcpInfo { addr: 127.0.0.1:1237 }) }]
DEBUG ledger_lib::provider::context: LedgerProvider response: Devices([LedgerInfo { model: Unknown(00), conn: Tcp(TcpInfo { addr: 127.0.0.1:1237 }) }])
DEBUG ledger_cli: Connecting to device: LedgerInfo { model: Unknown(0), conn: Tcp(TcpInfo { addr: 127.0.0.1:1237 }) }
DEBUG ledger_lib::provider::context: LedgerProvider request: Connect(LedgerInfo { model: Unknown(00), conn: Tcp(TcpInfo { addr: 127.0.0.1:1237 }) })
DEBUG ledger_lib::transport: Connecting to device: LedgerInfo { model: Unknown(0), conn: Tcp(TcpInfo { addr: 127.0.0.1:1237 }) }
DEBUG ledger_lib::transport::tcp: Connecting to: TcpInfo { addr: 127.0.0.1:1237 }
DEBUG ledger_lib::provider::context: Connected device 0: TCP 127.0.0.1:1237
DEBUG ledger_lib::provider::context: LedgerProvider response: Handle(00)
DEBUG ledger_lib::provider::context: LedgerProvider request: Req(00, [80, 03, 01, 00, c0, 07, e0, 0d, 49, 6e, 32, 48, 76, bb, c8, 53, 1f, 2d, 9a, 82, bf, 15, 4d, 1a, 04, a5, 02, 18, ee, 74, cd, d3, 72, f7, 5a, 55, 1a, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 03, 8d, 7e, a4, c6, 80, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 53, 4e, 5f, 47, 4f, 45, 52, 4c, 49, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 01], 3s)
DEBUG ledger_lib::transport::tcp: TX: [00, 00, 00, c5, 80, 03, 01, 00, c0, 07, e0, 0d, 49, 6e, 32, 48, 76, bb, c8, 53, 1f, 2d, 9a, 82, bf, 15, 4d, 1a, 04, a5, 02, 18, ee, 74, cd, d3, 72, f7, 5a, 55, 1a, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 03, 8d, 7e, a4, c6, 80, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 53, 4e, 5f, 47, 4f, 45, 52, 4c, 49, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 01]
DEBUG ledger_lib::provider::context: LedgerProvider response: Error(Timeout)
DEBUG ledger_lib::provider::context: LedgerProvider request: Close(00)
DEBUG ledger_lib::provider::context: Closed device 0: Tcp(TcpInfo { addr: 127.0.0.1:1237 })
Error: Request timeout
```

For your information, in any case Speculos traces show that a response is properly sent back by the device.

Here is the output of `rustup show`:
```
Default host: aarch64-apple-darwin
rustup home:  /Users/yogh/.rustup

installed toolchains
--------------------

stable-aarch64-apple-darwin
nightly-aarch64-apple-darwin (default)

active toolchain
----------------

nightly-aarch64-apple-darwin (default)
rustc 1.72.0-nightly (114fb86ca 2023-06-15)
```

**Comment by ryankurte** [comment] 2023-06-16 21:06
hmm interesting, we're using the TCP connector for integration tests which throw around a lot of packets and i haven't seen this... is there any chance the firmware is taking more than 3s to respond / can you reproduce the problem if you increase the APDU timeout from 3s (say `--timeout=10s`)?

**Comment by ryankurte** [comment] 2023-06-16 22:27
if that's not the case it would also be useful to isolate whether the behaviour is due to the TcpTransport or LedgerProvider... i added a `provider` feature to the CLI [here](https://github.com/ledger-community/rust-ledger/compare/cli/test/provider-switch?expand=1) which will let you select between these to test.

**Comment by yogh333** [comment] 2023-06-19 10:24
Hello, I performed additional tests by either increasing timeout or disabling `provider` feature (using your branch) but I have the same behaviour: 2 times out of 3, I have a `Error: Request timeout`.

**Comment by yogh333** [comment] 2023-06-19 12:44
More information: it looks like, whatever the `provider` feature is enabled or not, from time to time, CLI gets stuck in 
`TcpDevice` `read_data` function:  [first call to `read_exact` never returns](https://github.com/ledger-community/rust-ledger/blob/cli/test/provider-switch/lib/src/transport/tcp.rs#L130)

**Comment by ryankurte** [comment] 2023-06-19 23:09
great work tracking that down! isolating the `provider` feature means it's not due to interaction between the two runtimes (main and thread-pinned provider ctx)... now we just have to work out what's up with `read_exact` 🙃

so this definitely doesn't occur on debian, unclear whether it's macos or m1 specific behaviour. the only thing i can -see- that might cause weird behaviour is that when we list devices we open and close a socket, then on connection we re-open this.

it looks like [speculos](https://github.com/LedgerHQ/speculos/blob/a6743b9383247929e165b026212f1f6a11af0e7c/speculos/mcu/apdu.py#L26) doesn't handle routing requests and responses to the same socket (in fact, assumes there will only be one open socket at a time), so if the initial socket isn't closed in time the APDU response might be getting sent to the wrong socket?
it would also make sense that we have not seen this in our integration tests as we manually establish connections rather than using the scan function.

one possible fix would be to explicitly close the socket following discovery, something like:
```patch
diff --git a/lib/src/transport/tcp.rs b/lib/src/transport/tcp.rs
index 1f6b3a1..6cfaba3 100644
--- a/lib/src/transport/tcp.rs
+++ b/lib/src/transport/tcp.rs
@@ -70,12 +70,15 @@ impl Transport for TcpTransport {
         // Check whether speculos socket is open on the default port
         let addr = SocketAddr::new(Ipv4Addr::new(127, 0, 0, 1).into(), 1237);

-        if let Ok(_s) = TcpStream::connect(&addr).await {
+        if let Ok(mut s) = TcpStream::connect(&addr).await {
             // TODO: fill in model if we can request this?
             devices.push(LedgerInfo {
                 conn: TcpInfo { addr }.into(),
                 model: Model::Unknown(0),
             });
+            // Close and drop the socket
+            let _ = s.shutdown().await;
+            drop(s);
         }

         Ok(devices)
```

are you able to test this fix? otherwise we can modify the scan to avoid opening an initial connection to speculos at all.

**Comment by yogh333** [comment] 2023-06-20 07:57
Hello, I have tested proposed fix, but still the same issue...I am trying to dig to see if I can provide further information...

**Comment by yogh333** [comment] 2023-06-20 11:07
Hello, I confirm that the issue is due to the opening of two sockets (when listing then connecting). I have reproduced the issue by using directly `TcpTransport`  and as soon as I connect twice in a row, the issue occurs. Using `shutdown` on the previous socket does not fix the issue (also note that according to the [doc](https://docs.rs/tokio/latest/tokio/net/struct.TcpStream.html#method.connect), `shutdown` will only shut down the stream in the write direction).

**Comment by yogh333** [comment] 2023-06-20 21:41
Hi, I have tested the PR but no device is detected this time. Looks like the `TcpListener::bind` succeeds :( For your information, maybe I forgot to provide a quite relevant information: I am running speculos inside a Docker container. Here is the command line enabling to launch speculos:
`docker run --rm -it -v $(pwd)/app:/speculos/apps --publish 5001:5001 --publish 1237:1237 speculos-runner --display headless --api-port 5001 --apdu-port 1237 --model nanosp --apiLevel 1 apps/nano-rapp-starknet/target/nanosplus/release/nano-rapp-starknet`

**Comment by ryankurte** [comment] 2023-06-21 01:54
> Looks like the TcpListener::bind succeeds :(

that makes it seem like docker on M1 is somehow exposing a local port _without_ binding it? i am very confused... does changing the bind address to `0.0.0.0` then result in a conflict? can you run `lsof` to list port bindings with speculos running (something like `sudo lsof -nP -i4TCP:$PORT | grep LISTEN`)?

**Comment by yogh333** [comment] 2023-06-21 07:12
Hi, this is the output of `lsof` cmd when running speculos in Docker:
`com.docker 3774 jerome.caporossi  303u  IPv6 0x41fb70d50f127bdf      0t0  TCP *:1237 (LISTEN)`

**Comment by yogh333** [comment] 2023-06-21 07:18
When using `0.0.0.0` as a the bind address:
```
cargo run -p ledger-cli -- --filters tcp --log-level "debug" apdu --cla 0x80 --ins 3 --p1 1 "07e00d496e324876bbc8531f2d9a82bf154d1a04a50218ee74cdd372f75a551a00000000000000000000000000000000000000000000000000038d7ea4c680000000000000000000000000000000000000000000000000534e5f474f45524c49000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001"
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running `target/debug/ledger-cli --filters tcp --log-level debug apdu --cla 0x80 --ins 3 --p1 1 07e00d496e324876bbc8531f2d9a82bf154d1a04a50218ee74cdd372f75a551a00000000000000000000000000000000000000000000000000038d7ea4c680000000000000000000000000000000000000000000000000534e5f474f45524c49000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001`
DEBUG ledger_cli: args: Args { cmd: Apdu { cla: 128, ins: 3, p1: 1, p2: 0, data: ApduData([7, 224, 13, 73, 110, 50, 72, 118, 187, 200, 83, 31, 45, 154, 130, 191, 21, 77, 26, 4, 165, 2, 24, 238, 116, 205, 211, 114, 247, 90, 85, 26, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 141, 126, 164, 198, 128, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 83, 78, 95, 71, 79, 69, 82, 76, 73, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]) }, index: 0, filters: Tcp, timeout: Duration(3s), log_level: LevelFilter::DEBUG }
DEBUG ledger_lib::transport: Initialising GenericTransport
DEBUG ledger_lib::provider::context: Starting ledger provider task
DEBUG ledger_lib::provider::context: LedgerProvider request: List(Tcp)
DEBUG ledger_lib::provider::context: LedgerProvider response: Devices([LedgerInfo { model: Unknown(00), conn: Tcp(TcpInfo { addr: 0.0.0.0:1237 }) }])
DEBUG ledger_cli: Connecting to device: LedgerInfo { model: Unknown(0), conn: Tcp(TcpInfo { addr: 0.0.0.0:1237 }) }
DEBUG ledger_lib::provider::context: LedgerProvider request: Connect(LedgerInfo { model: Unknown(00), conn: Tcp(TcpInfo { addr: 0.0.0.0:1237 }) })
DEBUG ledger_lib::transport: Connecting to device: LedgerInfo { model: Unknown(0), conn: Tcp(TcpInfo { addr: 0.0.0.0:1237 }) }
DEBUG ledger_lib::transport::tcp: Connecting to: TcpInfo { addr: 0.0.0.0:1237 }
DEBUG ledger_lib::provider::context: Connected device 0: TCP 0.0.0.0:1237
DEBUG ledger_lib::provider::context: LedgerProvider response: Handle(00)
DEBUG ledger_lib::provider::context: LedgerProvider request: Req(00, [80, 03, 01, 00, c0, 07, e0, 0d, 49, 6e, 32, 48, 76, bb, c8, 53, 1f, 2d, 9a, 82, bf, 15, 4d, 1a, 04, a5, 02, 18, ee, 74, cd, d3, 72, f7, 5a, 55, 1a, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 03, 8d, 7e, a4, c6, 80, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 53, 4e, 5f, 47, 4f, 45, 52, 4c, 49, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 01], 3s)
DEBUG ledger_lib::transport::tcp: TX: [00, 00, 00, c5, 80, 03, 01, 00, c0, 07, e0, 0d, 49, 6e, 32, 48, 76, bb, c8, 53, 1f, 2d, 9a, 82, bf, 15, 4d, 1a, 04, a5, 02, 18, ee, 74, cd, d3, 72, f7, 5a, 55, 1a, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 03, 8d, 7e, a4, c6, 80, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 53, 4e, 5f, 47, 4f, 45, 52, 4c, 49, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 01]
DEBUG ledger_lib::transport::tcp: RX: [00, 00, 00, 01, 00, 90, 00]
DEBUG ledger_lib::provider::context: LedgerProvider response: Resp([00, 90, 00])
Response: 009000
DEBUG ledger_lib::provider::context: LedgerProvider request: Close(00)
DEBUG ledger_lib::provider::context: Closed device 0: Tcp(TcpInfo { addr: 0.0.0.0:1237 })
```

**Comment by yogh333** [comment] 2023-06-21 07:35
Last but not least, I have added the following code: 
```diff
diff --git a/lib/src/transport/tcp.rs b/lib/src/transport/tcp.rs
index 4d2f111..dafeb62 100644
--- a/lib/src/transport/tcp.rs
+++ b/lib/src/transport/tcp.rs
@@ -73,7 +73,10 @@ impl Transport for TcpTransport {
         // We can't -connect- to speculos as this does not handle multiple TCP connections
         // so instead we attempt to bind to the socket we expect speculos to occupy.
         match TcpListener::bind(addr.clone()).await {
-            Ok(_) => (),
+            Ok(l) => {
+                debug!("binding successful!");
+                debug!("{:?}", l.local_addr().unwrap());
+            },
             // A failure indicates this is in use and we should report a device available for connection
             Err(_) => {
                 devices.push(LedgerInfo {
```
I am running speculos with the same cmd as https://github.com/ledger-community/rust-ledger/issues/1#issuecomment-1599601044 and here is the output:
```
cargo run -p ledger-cli -- --filters tcp --log-level "debug" apdu --cla 0x80 --ins 3 --p1 1 "07e00d496e324876bbc8531f2d9a82bf154d1a04a50218ee74cdd372f75a551a00000000000000000000000000000000000000000000000000038d7ea4c680000000000000000000000000000000000000000000000000534e5f474f45524c49000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001"
   Compiling ledger-lib v0.1.0 (/Users/jerome.caporossi/Documents/Ledger/rust-ledger/lib)
   Compiling ledger-cli v0.1.0 (/Users/jerome.caporossi/Documents/Ledger/rust-ledger/cli)
    Finished dev [unoptimized + debuginfo] target(s) in 1.33s
     Running `target/debug/ledger-cli --filters tcp --log-level debug apdu --cla 0x80 --ins 3 --p1 1 07e00d496e324876bbc8531f2d9a82bf154d1a04a50218ee74cdd372f75a551a00000000000000000000000000000000000000000000000000038d7ea4c680000000000000000000000000000000000000000000000000534e5f474f45524c49000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001`
DEBUG ledger_cli: args: Args { cmd: Apdu { cla: 128, ins: 3, p1: 1, p2: 0, data: ApduData([7, 224, 13, 73, 110, 50, 72, 118, 187, 200, 83, 31, 45, 154, 130, 191, 21, 77, 26, 4, 165, 2, 24, 238, 116, 205, 211, 114, 247, 90, 85, 26, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 141, 126, 164, 198, 128, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 83, 78, 95, 71, 79, 69, 82, 76, 73, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]) }, index: 0, filters: Tcp, timeout: Duration(3s), log_level: LevelFilter::DEBUG }
DEBUG ledger_lib::transport: Initialising GenericTransport
DEBUG ledger_lib::provider::context: Starting ledger provider task
DEBUG ledger_lib::provider::context: LedgerProvider request: List(Tcp)
DEBUG ledger_lib::transport::tcp: binding successful!
DEBUG ledger_lib::transport::tcp: 127.0.0.1:1237
DEBUG ledger_lib::provider::context: LedgerProvider response: Devices([])
Error: No devices found
```
This is really confusing indeed....

**Comment by ryankurte** [comment] 2023-06-21 08:21
> When using 0.0.0.0 as a the bind address:

this appears to be working fine? i have also made this change to #2

**Comment by yogh333** [comment] 2023-06-21 08:25
Yes it works fine with `0.0.0.0` as the bind address....

**Closed as completed** 2023-06-23 04:15 UTC
